model:
  onnx_path: vnncomp2022_benchmarks/benchmarks/mnist_fc/onnx/mnist-net_256x2_ext4.onnx

specification:
  vnnlib_path: vnncomp2022_benchmarks/benchmarks/mnist_fc/vnnlib/prop_0_0.03_alt.vnnlib

solver:
  batch_size: 64

bab:
  timeout: 30